#heading(numbering: none)[Appendix]

== Training Level Set <appendix-training-levels>

This appendix lists the levels used to train agents in the transfer experiment (@transfer-experiment). All levels were generated by the cooperative generator framework and certified by the SAT-based acceptance oracle. For each level, the grid size, agent count, laser count, and cooperation profile are reported.

_To be completed: insert level images and parameter table here._


== Benchmark Levels for SAT Encoding Comparison <appendix-benchmark-levels>

The four levels used in the SAT encoding comparison (@experiments) are shown below with their
exact parameters.

#figure(
  table(
    columns: 5,
    stroke: black,
    inset: 8pt,
    align: horizon,
    table.header([*Level*], [*Grid*], [*Agents*], [*Lasers*], [*Horizon $T_"max"$*]),
    [Synthetic 3×3], [3×3], [2], [1], [8],
    [Synthetic 5×5], [5×5], [3], [2], [12],
    [Synthetic 8×8], [8×8], [4], [3], [32],
    [Benchmark Level 6], [varies], [4], [3], [known],
  ),
  caption: [Parameters of the four benchmark levels used in the SAT encoding comparison.],
)

#figure(
  grid(
    columns: 4,
    gutter: 8pt,
    align: center,
    [*3×3*], [*5×5*], [*8×8*], [*Level 6*],
    image("../../results/MLG-Student-Day/level_3x3_agents_2_lasers_1.png", width: 100%),
    image("../../results/MLG-Student-Day/level_5x5_agents_3_lasers_2.png", width: 100%),
    image("../../results/MLG-Student-Day/level_8x8_agents_4_lasers_3.png", width: 100%),
    image("../../results/MLG-Student-Day/level_lle_level6.png", width: 100%),
  ),
  caption: [Visual representation of the four benchmark levels.],
)


== Generator Parameters <appendix-generator-params>

#figure(
  table(
    columns: 4,
    stroke: black,
    inset: 8pt,
    align: horizon,
    table.header([*Parameter*], [*3×3*], [*5×5*], [*8×8*]),
    [Agents], [2], [3], [4],
    [Lasers], [1], [2], [3],
    [$T_"max"$ (rejection benchmark)], [8], [12], [20],
    [$T_"max"$ (profile benchmark)], [—], [12], [14],
    [Trials (rejection benchmark)], [200], [200], [20],
    [Max attempts per trial (rejection benchmark)], [500], [500], [100],
    [Trial timeout, s (rejection benchmark, $8 times 8$ only)], [—], [—], [30],
    [Levels generated (profile benchmark)], [—], [100], [50],
  ),
  caption: [Generator parameters used in the rejection rate and profile distribution benchmarks.],
)


== Cooperation Profile Examples <appendix-profile-examples>

The cooperation profile analyzer classifies accepted cooperative levels into five structural
families based on the inter-agent dependency graph. The definitions are given in @generators.
Representative visual examples of each profile type are provided below once the generator
benchmarks are completed.

- *Asymmetric*: Agent A depends on Agent B, but not vice versa.
- *Mutual*: Agents A and B each depend on the other.
- *Chain*: Dependencies form a directed chain A → B → C.
- *Distributed*: One agent depends on multiple distinct helpers.
- *Fully coupled*: All agents belong to a single strongly connected dependency component.

_To be completed: insert representative level images for each profile type._


== Learnability and Curriculum Hyperparameters <appendix-learnability-hyperparams>

The learnability experiment (@learnability-experiment) and the curriculum-transfer experiment
(@transfer-experiment) share the same trainer construction in
`src/experiments/learnability/run_experiment.py` and
`src/experiments/curriculum/run_experiment.py`. The hyperparameters listed in
@tab-learnability-hyperparams are identical across the three algorithms (IQL, VDN, QMIX) and
across both phases of the learnability experiment, as well as across the four conditions
(B1, B2, B3, CURR) of the curriculum-transfer experiment.

#figure(
  table(
    columns: 3,
    stroke: black,
    inset: 8pt,
    align: (horizon, center, left),
    table.header([*Hyperparameter*], [*Value*], [*Source*]),
    [Optimiser],                                  [Adam],                       [`marl.algos.{DQN,VDN,QMix}` default],
    [Learning rate],                              [$5 times 10^(-4)$],          [`run_experiment.py` (`lr=5e-4`)],
    [Batch size],                                 [64],                         [`run_experiment.py` (`batch_size=64`)],
    [Discount factor $gamma$],                    [0.95],                       [`run_experiment.py` (`gamma=0.95`)],
    [Train interval],                             [1 update / 5 env steps],     [`run_experiment.py` (`train_interval=(5,"step")`)],
    [Gradient-norm clipping],                     [10.0],                       [`run_experiment.py` (`grad_norm_clipping=10`)],
    [$epsilon$ schedule (train)],                 [linear $1.0 -> 0.05$ over 100,000 steps], [`EpsilonGreedy.linear(1.0, 0.05, 100_000)`],
    [Evaluation policy],                          [greedy ($epsilon = 0$)],     [`ArgMax()`],
    [Q-network architecture],                     [marl `qnetworks.from_env` default], [TODO: confirm exact RNN topology in marl],
    [Mixer (QMIX)],                               [`mixers.QMix.from_env`],     [`run_experiment.py`],
    [Mixer (VDN)],                                [sum of agent $Q$-values],    [`marl.algos.VDN` implicit mixer],
    [Mixer (IQL)],                                [none],                       [`run_experiment.py` (`mixer=None`)],
    [Independent $Q$-network heads (IQL, VDN)],   [yes],                        [`qnetworks.from_env(..., independent=True)`],
    [Independent $Q$-network heads (QMIX)],       [no (shared)],                [`qnetworks.from_env(...)` default],
    [Replay buffer size],                         [marl default],               [TODO: confirm in marl source],
    [Target network update interval],             [marl default],               [TODO: confirm in marl source],
  ),
  caption: [
    Hyperparameters used in both the learnability experiment
    (@learnability-experiment) and the curriculum-transfer experiment (@transfer-experiment).
    Rows marked as marl defaults inherit from the upstream marl framework
    (`C:/Users/hugoc/Projects/marl`); the commit pinned for these runs is recorded in
    `results/learnability/runs/marl_commit.txt`.
  ],
) <tab-learnability-hyperparams>


== Learnability Pool Samples — Phase 1 <appendix-learnability-p1>

The Phase 1 cooperative pool is a 6×6 grid with 2 agents and 1 laser, horizon $T_("max") = 10$,
generated by the `cooperative` registry generator. Pool-generation parameters are recorded in
`results/learnability/levels/6x6_2a_1L_cooperative/params.json` (train seed 20260515, test seed
20260516, 20 levels per split).

#figure(
  grid(
    columns: 3,
    gutter: 6pt,
    align: center,
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/train/images/level_000.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/train/images/level_001.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/train/images/level_002.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/train/images/level_003.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/train/images/level_004.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/train/images/level_005.png", width: 100%),
  ),
  caption: [
    Six representative training levels from the Phase 1 cooperative pool
    (6×6, 2 agents, 1 laser, $T_("max") = 10$, generator `cooperative`).
  ],
) <fig-learnability-p1-train-samples>

#figure(
  grid(
    columns: 3,
    gutter: 6pt,
    align: center,
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/test/images/level_000.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/test/images/level_001.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/test/images/level_002.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/test/images/level_003.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/test/images/level_004.png", width: 100%),
    image("../../results/learnability/levels/6x6_2a_1L_cooperative/test/images/level_005.png", width: 100%),
  ),
  caption: [
    Six representative held-out test levels from the Phase 1 cooperative pool
    (6×6, 2 agents, 1 laser, $T_("max") = 10$, generator `cooperative`).
  ],
) <fig-learnability-p1-test-samples>


== Learnability Pool Samples — Phase 2 <appendix-learnability-p2>

The Phase 2 cooperative pool is an 8×8 grid with 3 agents and 2 lasers, horizon
$T_("max") = 16$, generated by the `cooperative` registry generator. Pool-generation parameters
are recorded in `results/learnability_phase2/levels/8x8_3a_2L_cooperative/params.json`.

#figure(
  grid(
    columns: 3,
    gutter: 6pt,
    align: center,
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/train/images/level_000.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/train/images/level_001.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/train/images/level_002.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/train/images/level_003.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/train/images/level_004.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/train/images/level_005.png", width: 100%),
  ),
  caption: [
    Six representative training levels from the Phase 2 cooperative pool
    (8×8, 3 agents, 2 lasers, $T_("max") = 16$, generator `cooperative`).
  ],
) <fig-learnability-p2-train-samples>

#figure(
  grid(
    columns: 3,
    gutter: 6pt,
    align: center,
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/test/images/level_000.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/test/images/level_001.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/test/images/level_002.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/test/images/level_003.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/test/images/level_004.png", width: 100%),
    image("../../results/learnability_phase2/levels/8x8_3a_2L_cooperative/test/images/level_005.png", width: 100%),
  ),
  caption: [
    Six representative held-out test levels from the Phase 2 cooperative pool
    (8×8, 3 agents, 2 lasers, $T_("max") = 16$, generator `cooperative`).
  ],
) <fig-learnability-p2-test-samples>


== Curriculum Pool Samples — Stage 1 <appendix-curriculum-s1>

Stage 1 of the curriculum is a 6×6 grid with 4 agents and 1 laser, horizon $T_("max") = 12$,
generated by the `random` registry generator
(`constrained_random_solvable` in the thesis names). Pool seed: 20260614.

#figure(
  grid(
    columns: 3,
    gutter: 6pt,
    align: center,
    image("../../results/curriculum_experiment/levels/stage_1_6x6_4a_1L_random/train/images/level_000.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_1_6x6_4a_1L_random/train/images/level_001.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_1_6x6_4a_1L_random/train/images/level_002.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_1_6x6_4a_1L_random/train/images/level_003.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_1_6x6_4a_1L_random/train/images/level_004.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_1_6x6_4a_1L_random/train/images/level_005.png", width: 100%),
  ),
  caption: [
    Six representative training levels from curriculum stage 1
    (6×6, 4 agents, 1 laser, $T_("max") = 12$, generator `random`).
  ],
) <fig-curriculum-s1-samples>


== Curriculum Pool Samples — Stage 2 <appendix-curriculum-s2>

Stage 2 of the curriculum is an 8×8 grid with 4 agents and 2 lasers, horizon $T_("max") = 16$,
generated by the `cooperative` registry generator
(`constructive_cooperative` in the thesis names). Pool seed: 20260714.

#figure(
  grid(
    columns: 3,
    gutter: 6pt,
    align: center,
    image("../../results/curriculum_experiment/levels/stage_2_8x8_4a_2L_cooperative/train/images/level_000.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_2_8x8_4a_2L_cooperative/train/images/level_001.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_2_8x8_4a_2L_cooperative/train/images/level_002.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_2_8x8_4a_2L_cooperative/train/images/level_003.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_2_8x8_4a_2L_cooperative/train/images/level_004.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_2_8x8_4a_2L_cooperative/train/images/level_005.png", width: 100%),
  ),
  caption: [
    Six representative training levels from curriculum stage 2
    (8×8, 4 agents, 2 lasers, $T_("max") = 16$, generator `cooperative`).
  ],
) <fig-curriculum-s2-samples>


== Curriculum Pool Samples — Stage 3 <appendix-curriculum-s3>

Stage 3 of the curriculum is a 10×10 grid with 4 agents and 3 lasers, horizon
$T_("max") = 18$, generated by the `cooperative` registry generator. Pool seed: 20260814.

#figure(
  grid(
    columns: 3,
    gutter: 6pt,
    align: center,
    image("../../results/curriculum_experiment/levels/stage_3_10x10_4a_3L_cooperative/train/images/level_000.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_3_10x10_4a_3L_cooperative/train/images/level_001.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_3_10x10_4a_3L_cooperative/train/images/level_002.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_3_10x10_4a_3L_cooperative/train/images/level_003.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_3_10x10_4a_3L_cooperative/train/images/level_004.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_3_10x10_4a_3L_cooperative/train/images/level_005.png", width: 100%),
  ),
  caption: [
    Six representative training levels from curriculum stage 3
    (10×10, 4 agents, 3 lasers, $T_("max") = 18$, generator `cooperative`).
  ],
) <fig-curriculum-s3-samples>


== Curriculum Pool Samples — Stage 4 <appendix-curriculum-s4>

Stage 4 of the curriculum is a 12×13 grid with 4 agents and 3 lasers, horizon
$T_("max") = 21$, generated by the `level6_style` registry generator
(`constructive_level6_style` in the thesis names). Pool seeds: 20260914 (train), 20260915 (eval).
This stage is also the *transfer target* of the B1 baseline of @transfer-experiment.

#figure(
  grid(
    columns: 3,
    gutter: 6pt,
    align: center,
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/train/images/level_000.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/train/images/level_001.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/train/images/level_002.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/train/images/level_003.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/train/images/level_004.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/train/images/level_005.png", width: 100%),
  ),
  caption: [
    Six representative training levels from curriculum stage 4
    (12×13, 4 agents, 3 lasers, $T_("max") = 21$, generator `level6_style`).
  ],
) <fig-curriculum-s4-train-samples>

#figure(
  grid(
    columns: 3,
    gutter: 6pt,
    align: center,
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/eval/images/level_000.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/eval/images/level_001.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/eval/images/level_002.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/eval/images/level_003.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/eval/images/level_004.png", width: 100%),
    image("../../results/curriculum_experiment/levels/stage_4_12x13_4a_3L_level6_style/eval/images/level_005.png", width: 100%),
  ),
  caption: [
    Six representative held-out evaluation levels from curriculum stage 4
    (12×13, 4 agents, 3 lasers, $T_("max") = 21$, generator `level6_style`).
    Used as the held-out generated test set for the B1 baseline of @transfer-experiment.
  ],
) <fig-curriculum-s4-eval-samples>


== Per-Seed Final Success Rates — Phase 1 <appendix-learnability-p1-results>

Per-seed final greedy success rates after 100,000 environment steps, evaluated over 200 episodes
per pool. Source: `results/learnability/runs/{algo}_seed{N}/final_results.json`.
All 60 runs (3 algorithms $times$ 20 seeds) reach $hat(s) = 1.000$ on both pools, so the mean is
$1.000$ and the standard deviation is $0.000$ for every algorithm.

#figure(
  table(
    columns: 7,
    stroke: black,
    inset: 6pt,
    align: center,
    table.header(
      [*Seed*],
      [*IQL train*], [*IQL test*],
      [*VDN train*], [*VDN test*],
      [*QMIX train*], [*QMIX test*],
    ),
    [0], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [1], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [2], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [3], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [4], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [5], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [6], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [7], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [8], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [9], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [10], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [11], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [12], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [13], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [14], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [15], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [16], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [17], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [18], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [19], [1.000], [1.000], [1.000], [1.000], [1.000], [1.000],
    [*mean*], [*1.000*], [*1.000*], [*1.000*], [*1.000*], [*1.000*], [*1.000*],
    [*std*],  [0.000], [0.000], [0.000], [0.000], [0.000], [0.000],
  ),
  caption: [
    Phase 1: per-seed final greedy success rate after 100,000 environment steps. Each cell is the
    fraction of 200 evaluation episodes in which all agents reached an exit. Mean and standard
    deviation are computed across the 20 seeds in the column.
  ],
) <tab-learnability-p1-perseed>


== Per-Seed Final Success Rates — Phase 2 <appendix-learnability-p2-results>

Per-seed final greedy success rates after 200,000 environment steps, evaluated over 200 episodes
per pool. Source: `results/learnability_phase2/runs/{algo}_seed{N}/final_results.json`. The mean
and standard deviation rows are taken over all listed seeds for that algorithm (including the
QMIX re-run; see footnote).

#figure(
  table(
    columns: 7,
    stroke: black,
    inset: 6pt,
    align: center,
    table.header(
      [*Seed*],
      [*IQL train*], [*IQL test*],
      [*VDN train*], [*VDN test*],
      [*QMIX train*], [*QMIX test*],
    ),
    [0#super[\*]], [0.000], [0.000], [0.000], [0.000], [0.000], [0.000],
    [1], [0.000], [0.000], [1.000], [0.955], [1.000], [0.985],
    [2], [0.000], [0.000], [0.955], [1.000], [1.000], [1.000],
    [3], [0.000], [0.000], [0.000], [0.000], [1.000], [1.000],
    [4], [0.000], [0.000], [0.965], [1.000], [0.000], [0.000],
    [5], [0.535], [0.445], [1.000], [1.000], [0.965], [0.965],
    [6], [0.130], [0.130], [0.700], [0.960], [0.000], [0.000],
    [7], [0.000], [0.000], [0.860], [1.000], [1.000], [1.000],
    [8], [0.000], [0.000], [0.000], [0.000], [1.000], [1.000],
    [9], [0.070], [0.210], [1.000], [0.930], [1.000], [1.000],
    [10], [0.110], [0.060], [0.940], [1.000], [1.000], [0.965],
    [11], [0.000], [0.000], [0.930], [0.760], [1.000], [1.000],
    [12], [0.000], [0.000], [0.085], [0.000], [0.905], [0.960],
    [13], [1.000], [0.970], [0.640], [0.705], [0.930], [1.000],
    [14], [0.040], [0.065], [0.000], [0.000], [1.000], [1.000],
    [15], [0.000], [0.000], [0.910], [1.000], [1.000], [1.000],
    [16], [0.255], [0.210], [0.000], [0.000], [1.000], [1.000],
    [17], [0.115], [0.120], [1.000], [0.950], [1.000], [1.000],
    [18], [0.000], [0.000], [0.960], [0.930], [1.000], [1.000],
    [19], [1.000], [1.000], [0.000], [0.000], [1.000], [1.000],
    [42#super[\*\*]], [--], [--], [--], [--], [1.000], [0.970],
    [*mean*], [*0.163*], [*0.161*], [*0.597*], [*0.610*], [*0.848*], [*0.850*],
    [*std*],  [0.306], [0.296], [0.439], [0.453], [0.347], [0.347],
  ),
  caption: [
    Phase 2: per-seed final greedy success rate after 200,000 environment steps. Each cell is the
    fraction of 200 evaluation episodes in which all agents reached an exit. \
    #super[\*] Seed 0 of QMIX completed only 50,000 of the 200,000 step budget (partial run); the
    value is reported as-is and is included in the QMIX mean / std. \
    #super[\*\*] Seed 42 of QMIX is an additional 200,000-step run added to compensate for the
    seed 0 partial. The IQL and VDN columns of this row are empty by design (only QMIX was re-run).
  ],
) <tab-learnability-p2-perseed>
