#heading(numbering: none)[Appendix]

== Training Level Set <appendix-training-levels>

This appendix lists the levels used to train agents in the transfer experiment (@transfer-experiment). All levels were generated by the cooperative generator framework and certified by the SAT-based acceptance oracle. For each level, the grid size, agent count, laser count, and cooperation profile are reported.

_To be completed: insert level images and parameter table here._


== Benchmark Levels for SAT Encoding Comparison <appendix-benchmark-levels>

The four levels used in the SAT encoding comparison (@experiments) are shown below with their
exact parameters.

#figure(
  table(
    columns: 5,
    stroke: black,
    inset: 8pt,
    align: horizon,
    table.header([*Level*], [*Grid*], [*Agents*], [*Lasers*], [*Horizon $T_"max"$*]),
    [Synthetic 3×3], [3×3], [2], [1], [8],
    [Synthetic 5×5], [5×5], [3], [2], [12],
    [Synthetic 8×8], [8×8], [4], [3], [32],
    [Benchmark Level 6], [varies], [4], [3], [known],
  ),
  caption: [Parameters of the four benchmark levels used in the SAT encoding comparison.],
)

#figure(
  grid(
    columns: 4,
    gutter: 8pt,
    align: center,
    [*3×3*], [*5×5*], [*8×8*], [*Level 6*],
    image("../../results/MLG-Student-Day/level_3x3_agents_2_lasers_1.png", width: 100%),
    image("../../results/MLG-Student-Day/level_5x5_agents_3_lasers_2.png", width: 100%),
    image("../../results/MLG-Student-Day/level_8x8_agents_4_lasers_3.png", width: 100%),
    image("../../results/MLG-Student-Day/level_lle_level6.png", width: 100%),
  ),
  caption: [Visual representation of the four benchmark levels.],
)


== Generator Parameters <appendix-generator-params>

#figure(
  table(
    columns: 4,
    stroke: black,
    inset: 8pt,
    align: horizon,
    table.header([*Parameter*], [*3×3*], [*5×5*], [*8×8*]),
    [Agents], [2], [3], [4],
    [Lasers], [1], [2], [3],
    [$T_"max"$], [8], [12], [20],
    [Trials (rejection benchmark)], [50], [50], [20],
    [Max attempts per trial (rejection benchmark)], [500], [500], [500],
    [Levels generated (profile benchmark)], [—], [100], [10],
  ),
  caption: [Generator parameters used in the rejection rate and profile distribution benchmarks.],
)


== Cooperation Profile Examples <appendix-profile-examples>

The cooperation profile analyzer classifies accepted cooperative levels into five structural
families based on the inter-agent dependency graph. The definitions are given in @generators.
Representative visual examples of each profile type are provided below once the generator
benchmarks are completed.

- *Asymmetric*: Agent A depends on Agent B, but not vice versa.
- *Mutual*: Agents A and B each depend on the other.
- *Chain*: Dependencies form a directed chain A → B → C.
- *Distributed*: One agent depends on multiple distinct helpers.
- *Fully coupled*: All agents belong to a single strongly connected dependency component.

_To be completed: insert representative level images for each profile type._
